### ISSUE TITLE
Further enhancements for Gifymonster

### ISSUE THREAD

**Issue by RidhikGovind** [RidhikGovind/gifymonster#2]
Any new functionality ideas that  can be  implemented for Gifymonster can be discussed here.

**Comment by immayurpanchal** [comment]
1. Dark theme support can be added 

1. Clicking on image should copy the gif URL in the clipboard 

1. Instead of showing single GIF there can be multiple GIFs

**Comment by immayurpanchal** [comment]
@RidhikGovind , Are you accepting any pull requests under hacktoberfest ?

**Comment by RidhikGovind** [comment]
@immayurpanchal Hey thank you for your interest, but currently I am not accepting a pull requests. Good Luck mate !
